---
apiVersion: v1
kind: Secret
metadata:
  name: db-password
  namespace: bggns
type: Opaque
data:
  BGG_DB_PASSWORD: Y2hhbmdlaXQ=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: bggns
data:
  BGG_DB_USER: root
  BGG_DB_HOST: bggdb-svc.bggns.svc.cluster.local

---
apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: bggapp-deploy
  namespace: bggns
  labels:
    app: bggapp
    name: bggapp-deploy
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: 3
  selector:
    matchLabels:
      app: bggapp-app
  template:
    metadata:
      name: bggapp
      namespace: bggns
      labels:
        app: bggapp-app
    spec:
      containers:
      - name: bggapp-container
        image: stackupiss/bgg-backend:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: db-config
        - secretRef:
            name: db-password
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  namespace: bggns
  labels:
    app: bggapp
    name: bggapp-svc
spec:
  type: LoadBalancer
  selector:
    app: bggapp-app
  ports:
  - port: 80
    targetPort: 3000