apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: dov-deploy
  namespace: myns
  labels:
    app: dov
    name: dov-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      dept: eng
      commit: abc123
  template:
    metadata:
      name: pod-example
      namespace: myns
      labels:
        app: myapp
        dept: eng
        commit: abc123
    spec:
      containers:
      - name: bearbearbearbear
        image: chukmunnlee/dov-bear@sha256:9b004cdffbe1e3cbab18d8c18da71021d12825210c37f3ad8e9de5a23b67e1f7
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: INSTANCE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: INSTANCE_HASH
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['pod-template-hash']


---
apiVersion: v1
kind: Service
metadata:
  name: dov-svc
  namespace: myns
  labels:
    app: dov
    name: dov-svc
spec:
  type: ClusterIP
  selector:
    app: myapp
    dept: eng
    commit: abc123
  ports:
  - port: 8000
    targetPort: 3000
